/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.8.1/userguide/tutorial_java_projects.html
 */

group = "ch.peters.daniel"
version = "1.0"

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building an application
    application

    // Apply the groovy plugin to also add support for Groovy (needed for Spock)
    groovy
}

application {
    applicationName = "recursion"
    // Define the main class for the application
    mainClassName = "${project.group}.$applicationName.App"
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:23.0")

    // Use the latest Groovy version for Spock testing
    implementation("org.codehaus.groovy:groovy-all:2.4.14")

    // Use the awesome Spock testing and specification framework even with Java
    testImplementation("org.spockframework:spock-core:1.0-groovy-2.4")
    testImplementation("junit:junit:4.12")
}

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}
